In [29]:
import numpy as np

#Matrix multiplication


In [30]:
a = np.array([[1, -3, 2], [4, 0, -5]]) 
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [31]:
a.shape

(2, 3)

In [32]:
b = np.array([[3], [1], [2]]) 
print(b)

[[3]
 [1]
 [2]]


In [33]:
c = np.matmul(a, b) 
print(c)

[[4]
 [2]]


In [34]:
d = np.dot(a, b) 
print(d)

[[4]
 [2]]


In [35]:
d.shape

(2, 1)